### ISSUE TITLE
Lidarr Helm Chart Example using https://bjw-s.github.io/helm-charts

### ISSUE THREAD

**Issue by reefland** [onedr0p/exportarr#133]
Not a Bug Report, but the "Discuss on GitHub" option still points to "k8s-at-home" Github, couldn't use that.

The Kubernetes Examples, did not have a Helm Chart example. And the <https://github.com/onedr0p/home-ops/tree/main/kubernetes/apps/default/lidarr> does not make use of this `exportarr`.

I adapted `exportarr` to use <https://bjw-s.github.io/helm-charts> common chart for use in ArgoCD (easy to convert to FluxCD).  Just wanted to share it, might help someone else.

* I'm using 2 charts (lidarr and lidarr-exporter) within one ArgoCD application, to avoid name conflicts I included a `nameOverride: lidarr-exporter`.
* I deploy to namespace `nzb` instead of `default` , adjust your service URL as appropriate.

Relevant section:

```
    - chart: app-template
      repoURL: https://bjw-s.github.io/helm-charts
      targetRevision: 1.3.2
      helm:
        # https://github.com/onedr0p/exportarr/blob/master/examples/kubernetes/lidarr-exporter.yaml
        values: |
          global:
            nameOverride: lidarr-exporter

          controller:
            # Valid options are deployment, daemonset or statefulset
            type: deployment
            revisionHistoryLimit: 3

          image:
            repository: ghcr.io/onedr0p/exportarr
            # renovate: datasource=docker depName=ghcr.io/onedr0p/exportarr
            tag: "v1.2.4"
            pullPolicy: IfNotPresent
          args:
            - lidarr

          env:
            PORT: "9707"
            URL: "http://lidarr.nzb.svc.cluster.local:80"
            APIKEY:
              valueFrom:
                secretKeyRef:
                  name: lidarr-api-key
                  key: api-key

          service:
            main:
              ports:
                http:
                  port: 9707

          serviceMonitor:
            main:
              enabled: true
              endpoints:
                - port: http
                  interval: 4m
                  scrapeTimeout: 90s
                  path: /metrics

          probes:
            livenessProbe:
              httpGet:
                path: /healthz
                port: monitoring
              failureThreshold: 5
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /healthz
                port: monitoring
              failureThreshold: 5
              periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
```
Prometheus Picks up the Target:
![image](https://user-images.githubusercontent.com/16230914/226786734-2c336396-bbcb-4d65-aeb0-aa748771cc9f.png)

**Comment by reefland** [comment]
I could not figure out how to include a `prometheusRule` within this new common template. I wanted to include this as well:
```
            prometheusRule:
              enabled: true
              labels: {}
              # -- Configure additionial rules for the chart under this key.
              rules:
                - alert: LidarrDown
                  annotations:
                    description: Lidarr service is down.
                    summary: Lidarr is down.
                  expr: |
                    lidarr_system_status == 0
                  for: 5m
                  labels:
                    severity: critical
```

If anyone knows if this is possible....

**Comment by onedr0p** [comment]
`prometheusRule` are not part of the  common library / app template. But thanks for sharing!

**Comment by reefland** [comment]
I tried to put it under `sidecars:` as I saw that in the common template.  No error, but nothing rendered, seems to go ignored.  I did not have time to troubleshoot, and just put back the secondary chart.   I'll revisit it again. Thanks.

**Comment by reefland** [comment]
@rtrox - I was able to get `sidecars:` working, I assumed it would use same YAML syntax as the rest of chart, but a sidecar seems to require exact manifest content.  Once I made that change, started to work.

Update the existing application(lidarr) service, to include a monitoring port:
```
service:
  main:
    ports:
      http:
        port: *port
      monitoring:
        port: &monitoring_port 9707
```

Then at the bottom, place the `exportarr` contents:
```
# https://github.com/onedr0p/exportarr/blob/master/examples/kubernetes/lidarr-exporter.yaml
serviceMonitor:
  main:
    enabled: true
    endpoints:
      - port: monitoring
        interval: 4m
        scrapeTimeout: 90s
        path: /metrics

sidecars:
  exportarr:
    image: ghcr.io/onedr0p/exportarr:v1.2.4
    imagePullPolicy: IfNotPresent
    args:
      - lidarr

    env:
      PORT: "9707"
      URL: "http://lidarr.nzb.svc.cluster.local:80"
      ENABLE_ADDITIONAL_METRICS: true
      APIKEY:
        valueFrom:
          secretKeyRef:
            name: lidarr-api-key
            key: api-key

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

    ports:
      - name: monitoring
        containerPort: *monitoring_port
    livenessProbe:
      httpGet:
        path: /healthz
        port: monitoring
      failureThreshold: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: monitoring
      failureThreshold: 5
      periodSeconds: 10
```
