### ISSUE TITLE
Support installation via Kustomize

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/exportarr#184]
# Details

**Describe the solution you'd like:**

Give people the ability to install this with kustomize.

**Comment by onedr0p** [comment]
# Implementation details

Create a new directory under `kubernetes/kustomize` with the manifests needed so people can use kustomize to install this.

From a UX point of view installing exportarr with kustomize could be done something like this:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rancher/system-upgrade-controller?ref=v0.11.0
  - secret.yaml
images:
  - name: ghcr.io/onedr0p/exportarr
    newTag: v1.5.0
patchesStrategicMerge: [] # Override anything that is default
```
