### ISSUE TITLE
exportarr prefers port from config.xml instead of CLI flag

### ISSUE THREAD

**Issue by volker-raschek** [onedr0p/exportarr#276]
Hi there, 
I've tried to get exportarr running on kubernetes, but it seems that exportarr preferes the port of the `config.xml` instead of the port configured via CLI flag `--url`. I belive the same error also exists for radarr, readarr, sonarr and prowlarr. 

I declared in my current set up a kubernetes service to forward incoming traffic to each instance of a lidarr pod. The port where the application (pod) is listening on is the default - like for lidarr `8686`. 

To access lidarr via app or browser I need to change the service type from `ClusterIP` to `LoadBalancer`. This is no problem for me, because the kubernetes cluster is running locally and can not access via internet. For user-friendliness I've changed the port of the service from `8686` to `80`. Lidarr can therefore be opened directly in the browser without specifying a port, because port `80` is the default. The incoming data traffic is therefore forwarded from port `80` of the kubernetes service to port `8686` of the lidarr instance.

Now to exportarr. I have provided the `config.xml` of lidarr via `volumeMount` to exportarr and specified the absolute file path via the `--config` flag. Since exportarr now reads the config and finds the port `8686` there, exportarr tries to reach the lidarr API via this port. However, this is not possible because the port is not released by the service. 

```text
2024-03-03T15:12:18.758Z        INFO    Starting exportarr      {"app_name": "exportarr", "version": "v1.5.3", "buildTime": "2023-06-14T18:41:40.589Z", "revision": "952a768edf22789f6b07005cdce18898c1ef3a2a"}
2024-03-03T15:12:18.760Z        INFO    Starting HTTP Server    {"interface": "0.0.0.0", "port": 9707}
2024-03-03T15:13:00.728Z        INFO    Sending HTTP request    {"url": "http://lidarr:8686/api/v1/system/status"}
2024-03-03T15:13:00.730Z        INFO    Sending HTTP request    {"url": "http://lidarr:8686/api/v1/health"}
2024-03-03T15:13:00.731Z        INFO    Sending HTTP request    {"url": "http://lidarr:8686/api/v1/artist"}
2024-03-03T15:13:00.731Z        INFO    Sending HTTP request    {"url": "http://lidarr:8686/api/v1/queue?page=1"}
2024-03-03T15:13:00.731Z        INFO    Sending HTTP request    {"url": "http://lidarr:8686/api/v1/history"}
2024-03-03T15:13:00.731Z        INFO    Sending HTTP request    {"url": "http://lidarr:8686/api/v1/rootfolder"}
2024-03-03T15:13:02.778Z        ERROR   Error getting rootfolder        {"collector": "rootfolder", "error": "Failed to execute HTTP Request(http://lidarr:8686/api/v1/rootfolder): Get \"http://lidarr:8686/api/v1/rootfolder\": Error sending HTTP Request: dial tcp 10.100.75.74:8686: connect: connection refused"}
```

My exportarr deployment. The URL of the flag `--url` points to the service `lidarr`, port `80`.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: lidarr
    meta.helm.sh/release-namespace: media
  labels:
    app.kubernetes.io/instance: lidarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: lidarr-exportarr
    app.kubernetes.io/version: 1.4.5
    helm.sh/chart: lidarr-0.1.0-exportarr
  name: lidarr-exportarr
  namespace: media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: lidarr
      app.kubernetes.io/name: lidarr-exportarr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: lidarr
        app.kubernetes.io/name: lidarr-exportarr
    spec:
      containers:
      - args:
        - lidarr
        - --config=/config/config.xml
        - --port=9707
        - --url=http://lidarr:80
        image: ghcr.io/onedr0p/exportarr:v1.5.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: monitoring
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: exportarr
        ports:
        - containerPort: 9707
          name: monitoring
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: monitoring
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: lidarr-config
```

### UPDATE

The bug also exists in the latest version - `v1.6.2`.

### Workaround 

1. Remove the volume mount of the `config.xml` file.
2. Start lidarr
3. Extract the API key via GUI
4. Define the API key via `--api-key` flag.
5. Exportarr use the specified port as part of the `--url` flag as expected

Volker
