### ISSUE TITLE
[v2.0.1] doesn't seem to work, just keeps giving its commands/flags over and over

### ISSUE THREAD

**Issue by evanrich** [onedr0p/exportarr#289]
using the following config:
```
exportarr:
        image:
          repository: ghcr.io/onedr0p/exportarr
          pullPolicy: IfNotPresent
          tag: v2.0.1
        env:
          PORT: "9707"
          URL: "http://radarr.default.svc.cluster.local:7878"
          API_KEY:
            valueFrom:
              secretKeyRef:
                name: radarr-api-key
                key: radarr_api_key
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: http
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
```
it just keeps spitting out the following once the container runs
```
exportarr is a Prometheus exporter for *arr applications.
It can export metrics from Radarr, Sonarr, Lidarr, Readarr, Bazarr and Prowlarr.
More information available at the Github Repo (https://github.com/onedr0p/exportarr)

Usage:
  exportarr [command]

Available Commands:
  bazarr      Prometheus Exporter for Bazarr
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  lidarr      Prometheus Exporter for Lidarr
  prowlarr    Prometheus Exporter for Prowlarr
  radarr      Prometheus Exporter for Radarr
  readarr     Prometheus Exporter for Readarr
  sabnzbd     Prometheus Exporter for Sabnzbd
  sonarr      Prometheus Exporter for Sonarr

Flags:
  -a, --api-key string        API Key for *arr instance
      --api-key-file string   File containing API Key for *arr instance
      --disable-ssl-verify    Disable SSL verification
  -h, --help                  help for exportarr
  -i, --interface string      IP address to listen on
      --log-format string     Log format (console, json) (default "console")
  -l, --log-level string      Log level (debug, info, warn, error, fatal, panic) (default "info")
  -p, --port int              Port to listen on
  -u, --url string            URL to *arr instance

Use "exportarr [command] --help" for more information about a command.
```

I'm using this as a side car to the main radarr app
