### ISSUE TITLE
[Docker Compose] API_KEY_FILE woes

### ISSUE THREAD

**Issue by Lebowski89** [onedr0p/exportarr#304]
Hello,

Have used exportarr containers for a while on UnRaid without issue. I am now setting them up via Docker Compose on a Ubuntu server. I have been making use of docker secrets for various containers without issue, but I can't seem to get it to work with exportarr. Using -e value of API_KEY_FILE gives, 'regex: api-key must be a 20-32 character alphanumeric string'. I checked the actual API key and it is a 32 character alphanumeric string. I have also used this exact API to connect with Prowlarr and others, previously. I have also used the secrets file with the same API before in other containers with success (i.e, doplarr to connect with Radarr/Sonarr, for example). And, obviously, I have tried setting API_KEY with the API key and it works. It's just not liking docker secrets. 

Here is my docker-compose.yml (using Lidarr as an example):

```
  lidarr-exporter:
    container_name: '${LID_EXP_CONTAINER_NAME}'
    image: ghcr.io/onedr0p/exportarr:${EXPORTARR_IMAGE_TAG}
    networks:
      socket_proxy:
      traefik_proxy: 
      proxy:
    command: ["lidarr"]
    environment:
      PORT: '${LID_EXP_CONT_PORT}'
      #URL: 'https://${LIDARR_CONTAINER_NAME}.${DOMAINNAME_1}' # Traefik
      URL: 'http://${LIDARR_CONTAINER_NAME}:${LIDARR_PORT}' # Internal
      API_KEY_FILE: '/run/secrets/lidarr_api'
    ports:
      - '${LID_EXP_HOST_PORT}:${LID_EXP_CONT_PORT}'
    secrets:
      - pullio_webhook
      - lidarr_api
    env_file:
      - .env
    restart: unless-stopped

networks:
  socket_proxy:
    external: true
  traefik_proxy:
    external: true
  proxy:
    external: true

secrets:
  lidarr_api:
    file: '${SECRETS_PATH}/lidarr_api.txt'
```

.env

```
#GLOBAL#
PUID=1000
PGID=1000
UMASK=002
TZ=Australia/Melbourne
SECRETS_PATH=/appdata/ubuntu/docker/secrets
DOMAINNAME_1=[MYDOMAIN].com
ENABLE_ADDITIONAL_METRICS=true

#CONTAINER_NAME
LIDARR_CONTAINER_NAME=lidarr

## EXPORTERS
LID_EXP_CONTAINER_NAME=lidarr-exporter

#IMAGE_TAG
EXPORTARR_IMAGE_TAG=v2.0.1

#CONTAINER_PORTS
LIDARR_PORT=8686

## EXPORTARRS_HOST
LID_EXP_HOST_PORT=9709

## EXPORTARRS_CONTAINER
LID_EXP_CONT_PORT=9709
```

Have I done something wrong here? TIA

Screenshot of container log when I try use secret:
![Screenshot_54](https://github.com/onedr0p/exportarr/assets/149286193/712b03fa-9dff-4a0b-b19c-cc79c601f8ee)

Screenshots when I use API_KEY with key included in the docker-compose.yml:
![Screenshot_55](https://github.com/onedr0p/exportarr/assets/149286193/f742f285-f5e2-487c-90ad-68f7cae7e38a)
![Screenshot_56](https://github.com/onedr0p/exportarr/assets/149286193/2f4469b6-2383-4890-9594-c624584dac7a)
