### ISSUE TITLE
Running Multiple Instances Of Radarr, Sonarr, etc.

### ISSUE THREAD

**Issue by iamronr** [onedr0p/exportarr#313]
# Details

**Describe the solution you'd like:**
Adding different labels in Prometheus/Grafana for multiple instances of an app: Radarr, Radarr 4K

**Anything else you would like to add:**
I tried labeling them differently in Docker, but they show up the same in Prometheus and Grafana

Any feedback on this would be greatly appreciated. Here's my docker-compose, and my prometheus/xml and screenshot of how it currently shows. But I'd like to separate the two, and do the same for Sonarr, Bazarr, Prowlarr, etc as well...

```
  exportarr-radarr:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: exportarr-radarr
    env_file: server.env
    command: ["radarr"]
    environment:
      - PORT=9710
      - URL=$RMEDIAIP:7878
      - APIKEY=REDACTED
      - ENABLE_ADDITIONAL_METRICS=true
    ports:
      - 9710:9710
    restart: unless-stopped
  exportarr-radarr4k:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: exportarr-radarr4k
    env_file: server.env
    command: ["radarr"]
    environment:
      - PORT=9711
      - URL=$RMEDIAIP:7879
      - APIKEY=REDACTED
      - ENABLE_ADDITIONAL_METRICS=true
    ports:
      - 9711:9711
    restart: unless-stopped

```

```
  - job_name: 'exportarr-radarr'
    static_configs:
    - targets: ['localhost:9710']
  - job_name: 'exportarr-radarr4k'
    static_configs:
    - targets: ['localhost:9711']
```

![TRC](https://github.com/user-attachments/assets/3f6a763a-5bab-4906-ae69-95a5ac089cfc)
