### ISSUE TITLE
Include metric sonarr_episode_monitored_total

### ISSUE THREAD

**Issue by ngosang** [onedr0p/exportarr#80]
These metrics are available:
* sonarr_series_monitored_total
* sonarr_season_monitored_total

But this metric is missing:
* sonarr_episode_monitored_total

**Comment by onedr0p** [comment]
Post your configuration here.

**Comment by ngosang** [comment]
```yml
  sonarr-exporter:
    # https://github.com/onedr0p/exportarr  
    image: ghcr.io/onedr0p/exportarr:v1.1.0
    container_name: sonarr-exporter
    command: sonarr
    environment:
      - TZ=Europe/Madrid
      - PORT=9707
      - URL=http://sonarr:8989
      - APIKEY=xxxxx
    ports:
      - 9707:9707
    restart: unless-stopped
```

```
# HELP sonarr_episode_downloaded_total Total number of downloaded episodes
# TYPE sonarr_episode_downloaded_total gauge
sonarr_episode_downloaded_total{url="http://sonarr:8989"} 1984
# HELP sonarr_episode_missing_total Total number of missing episodes
# TYPE sonarr_episode_missing_total gauge
sonarr_episode_missing_total{url="http://sonarr:8989"} 6
# HELP sonarr_episode_total Total number of episodes
# TYPE sonarr_episode_total gauge
sonarr_episode_total{url="http://sonarr:8989"} 6377
# HELP sonarr_history_total Total number of item in the history
# TYPE sonarr_history_total gauge
sonarr_history_total{url="http://sonarr:8989"} 3183
# HELP sonarr_rootfolder_freespace_bytes Root folder space in bytes by path
# TYPE sonarr_rootfolder_freespace_bytes gauge
sonarr_rootfolder_freespace_bytes{path="/media/hdd_raid/MEDIA/TV_EN",url="http://sonarr:8989"} 4.87754123264e+12
sonarr_rootfolder_freespace_bytes{path="/media/hdd_raid/MEDIA/TV_ES",url="http://sonarr:8989"} 4.87754123264e+12
# HELP sonarr_season_downloaded_total Total number of downloaded seasons
# TYPE sonarr_season_downloaded_total gauge
sonarr_season_downloaded_total{url="http://sonarr:8989"} 194
# HELP sonarr_season_monitored_total Total number of monitored seasons
# TYPE sonarr_season_monitored_total gauge
sonarr_season_monitored_total{url="http://sonarr:8989"} 101
# HELP sonarr_season_total Total number of seasons
# TYPE sonarr_season_total gauge
sonarr_season_total{url="http://sonarr:8989"} 418
# HELP sonarr_season_unmonitored_total Total number of unmonitored seasons
# TYPE sonarr_season_unmonitored_total gauge
sonarr_season_unmonitored_total{url="http://sonarr:8989"} 395
# HELP sonarr_series_downloaded_total Total number of downloaded series
# TYPE sonarr_series_downloaded_total gauge
sonarr_series_downloaded_total{url="http://sonarr:8989"} 107
# HELP sonarr_series_filesize_bytes Total fizesize of all series in bytes
# TYPE sonarr_series_filesize_bytes gauge
sonarr_series_filesize_bytes{url="http://sonarr:8989"} 2.172801025421e+12
# HELP sonarr_series_monitored_total Total number of monitored series
# TYPE sonarr_series_monitored_total gauge
sonarr_series_monitored_total{url="http://sonarr:8989"} 21
# HELP sonarr_series_total Total number of series
# TYPE sonarr_series_total gauge
sonarr_series_total{url="http://sonarr:8989"} 129
# HELP sonarr_series_unmonitored_total Total number of unmonitored series
# TYPE sonarr_series_unmonitored_total gauge
sonarr_series_unmonitored_total{url="http://sonarr:8989"} 108
# HELP sonarr_system_status System Status
# TYPE sonarr_system_status gauge
sonarr_system_status{url="http://sonarr:8989"} 1

```
