### ISSUE TITLE
Radarr exporter uses too many resources

### ISSUE THREAD

**Issue by ngosang** [onedr0p/exportarr#87]
# Details

Radarr exporter uses too many resources compared to Sonarr and Lidarr exporters. My movie collection is not that big. Maybe you can take a look at the endpoints you are calling and optimize something.

* Radarr => 739 Movies
* Sonarr => 132 Series 6450 Episodes

exportarr: v1.1.0
ENABLE_ADDITIONAL_METRICS: false
ENABLE_UNKNOWN_QUEUE_ITEMS: false

My fix for now is to configure a huge scrape_interval in Prometheus.
```yaml
  - job_name: 'radarr-exporter'
    scrape_interval: 600s
    static_configs:
      - targets: ['192.168.1.191:9708']
```

![image](https://user-images.githubusercontent.com/10577978/190276292-8f81886c-2b08-4c79-8052-0c36b44e376d.png)

Update:
After I changed the scrape_interval, I can see Radarr is using less resources too:
![image](https://user-images.githubusercontent.com/10577978/190280715-55774e15-5834-401b-8969-9fae8df6b06b.png)
