### ISSUE TITLE
401 on metrics gathering

### ISSUE THREAD

**Issue by alexmobo** [onedr0p/exportarr#92]
# Details

**What steps did you take and what happened:**

I configured exportarr to gather metrics of sonarr and radarr. Both are getting a 401 when asking for metrics.
I have sonarr and radarr configurad with security.

<img width="679" alt="Captura de pantalla 2022-11-09 a las 19 02 20" src="https://user-images.githubusercontent.com/2112640/200905939-82ef8947-76e3-4126-85a2-6755b93a6653.png">

and I have added the environment variables for basic auth.

**What did you expect to happen:**

Gathering metrics wo a problem.

**Comment by onedr0p** [comment]
Please share the exportarr, sonarr and radarr versions you are using and your configuration for exportarr.

**Comment by alexmobo** [comment]
- Radarr Version: 4.2.4.6635
- Sonarr Version: 3.0.9.1549
- Exportarr Version: Latest (Can only see that tag in docker image. Image was created 2022-07-03T02:31:40.312380211Z and sha256 is aa44e535500e20c7f22f802cd19496c79ae4a982e24e9677f98ed5ea8ad3784e)

Radarr Exportarr config:
```yaml
    radarr-exportarr:
        image: ghcr.io/onedr0p/exportarr:latest
        container_name: radarr-exportarr
        expose:
            - "9708"
        command: radarr
        environment:
            - PORT=9708
            - URL=http://radarr:7878
            - API_KEY=xxx
            - ENABLE_ADDITIONAL_METRICS=true
            - BASIC_AUTH_USERNAME=xxx
            - BASIC_AUTH_PASSWORD=xxx
        restart: unless-stopped
```

Sonarr Exportarr config:
```yaml
    sonarr-exportarr:
        image: ghcr.io/onedr0p/exportarr:latest
        container_name: sonarr-exportarr
        expose:
            - "9707"
        command: sonarr
        environment:
            - PORT=9707
            - URL=http://sonarr:8989
            - API_KEY=xxx
            - ENABLE_ADDITIONAL_METRICS=true
            - BASIC_AUTH_USERNAME=xxx
            - BASIC_AUTH_PASSWORD=xxx
        restart: unless-stopped
```
